services:
  # ASP.NET application container
  webapp:
    image: pizzeriaapi-server:latest # The name of your app's image
    build: .
    ports:
      - "5283:8080"  # Expose the app's port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - my_secret=${MY_SECRET}
    depends_on:
        mydb:
            condition: service_healthy

  mydb:
    image: mysql:8.0  # MySQL Docker image
    environment:
      - MYSQL_ROOT_PASSWORD=${MY_SECRET_PASSWORD}
      - MYSQL_DATABASE=${MY_SECRET_DB}
      - MYSQL_USER=${MY_SECRET_USER}
      - MYSQL_PASSWORD=${MY_SECRET_PASSWORD}
    ports:
      - "3307:3306"  # Expose MySQL port
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 30s
        retries: 5
        start_period: 30s
        timeout: 10s

volumes:
  mysql-data: